# ==========================================================================
# Project:   ModuleProxyTest
# Copyright: @2012 My Company, Inc.
# ==========================================================================

# This is your Buildfile for your app, ModuleProxyTest. This tells SproutCore
# how to build your app. These settings override those in your project
# Buildfile, which contains default settings for all apps in your project.

# It is better to add :required targets here than in the global Buildfile.
config :module_proxy_test, 
		:required => [ :sproutcore, 'sproutcore/statechart'],                    
		:prefetched_modules => [ 'test']

